//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoJinFirst.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adddress_T
    {
        public Adddress_T()
        {
            this.Order_T = new HashSet<Order_T>();
        }
    
        public long Address_Id { get; set; }
        public string Address_City { get; set; }
        public string Address_Diqu { get; set; }
        public string Address_Phone { get; set; }
        public string Address_Lianxiren { get; set; }
        public Nullable<long> User_ID { get; set; }
    
        public virtual ICollection<Order_T> Order_T { get; set; }
    }
}
