//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoJinFirst.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Shopimage_T
    {
        public long ShopimageID { get; set; }
        public string shopImage { get; set; }
        public Nullable<long> Shop_Information_Id { get; set; }
    }
}
