//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoJinFirst.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus_User_T
    {
        public Menus_User_T()
        {
            this.User_Menus_Quanxian_T = new HashSet<User_Menus_Quanxian_T>();
        }
    
        public long Menus_ID { get; set; }
        public string Menus_Name { get; set; }
        public string Menus_icon { get; set; }
        public string Menus_Url { get; set; }
    
        public virtual ICollection<User_Menus_Quanxian_T> User_Menus_Quanxian_T { get; set; }
    }
}
