//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoJinFirst.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_T
    {
        public long News_ID { get; set; }
        public long News_Type_ID { get; set; }
        public string News_Title { get; set; }
        public string News_Image { get; set; }
        public string News_Content { get; set; }
        public string News_Describe { get; set; }
        public Nullable<System.DateTime> News_Releasetime { get; set; }
        public Nullable<System.DateTime> News_Backouttime { get; set; }
        public string News_IsorNo { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<long> User_TyID { get; set; }
    
        public virtual News_Type_T News_Type_T { get; set; }
        public virtual User_Information_T User_Information_T { get; set; }
        public virtual User_Type_T User_Type_T { get; set; }
    }
}
