//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoJinFirst.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_T
    {
        public long Order_Id { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<long> Shop_Information_Id { get; set; }
        public Nullable<System.DateTime> Order_time { get; set; }
        public Nullable<int> Order_State { get; set; }
        public Nullable<long> Address_Id { get; set; }
        public Nullable<int> Order_Count { get; set; }
        public Nullable<int> Order_Checked { get; set; }
        public Nullable<decimal> Order_Maney { get; set; }
    
        public virtual Adddress_T Adddress_T { get; set; }
        public virtual User_Information_T User_Information_T { get; set; }
    }
}
