//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoJinFirst.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Information_T
    {
        public User_Information_T()
        {
            this.News_T = new HashSet<News_T>();
            this.Order_T = new HashSet<Order_T>();
            this.User_Menus_Quanxian_T = new HashSet<User_Menus_Quanxian_T>();
            this.Video_T = new HashSet<Video_T>();
            this.wenzhang_T = new HashSet<wenzhang_T>();
        }
    
        public long User_ID { get; set; }
        public string User_Bieming { get; set; }
        public string User_Name { get; set; }
        public string User_PassWord { get; set; }
        public string User_Phone { get; set; }
        public string User_Image { get; set; }
        public string User_Address { get; set; }
        public string User_Number { get; set; }
        public Nullable<long> User_TyID { get; set; }
        public Nullable<int> User_Certification { get; set; }
        public Nullable<long> User_Vip_ID { get; set; }
        public Nullable<int> User_JIfen { get; set; }
    
        public virtual ICollection<News_T> News_T { get; set; }
        public virtual ICollection<Order_T> Order_T { get; set; }
        public virtual User_Type_T User_Type_T { get; set; }
        public virtual User_Vip_T User_Vip_T { get; set; }
        public virtual ICollection<User_Menus_Quanxian_T> User_Menus_Quanxian_T { get; set; }
        public virtual ICollection<Video_T> Video_T { get; set; }
        public virtual ICollection<wenzhang_T> wenzhang_T { get; set; }
    }
}
