//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuoJinFirst.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Type_T
    {
        public User_Type_T()
        {
            this.News_T = new HashSet<News_T>();
            this.Quanxian_T = new HashSet<Quanxian_T>();
            this.User_Information_T = new HashSet<User_Information_T>();
        }
    
        public int User_TyID { get; set; }
        public string User_TyName { get; set; }
        public string Icon { get; set; }
    
        public virtual ICollection<News_T> News_T { get; set; }
        public virtual ICollection<Quanxian_T> Quanxian_T { get; set; }
        public virtual ICollection<User_Information_T> User_Information_T { get; set; }
    }
}
